version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: ksdb_postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hari@123
      POSTGRES_DB: ksdb

    ports:
      - "5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: